### ISSUE TITLE
MTS Vehicles fall through the ground

### ISSUE THREAD

**Issue by Nianor** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#170] opened 2018-06-13 20:02 UTC
What it says on the tin. All vehicles from MTS will fall through the ground when placed, even if no VW ships have been used or created. The vehicles from MTS simply don't collide with the ground anymore.

**Comment by Nimbleguy** [comment] 2018-06-14 23:33
I'm having the same issue. It also causes Ancient Warfare 2 models to be offset, somehow. This happens even in new worlds before anything from Valkyrien Warfare is interacted with.

**Comment by Zundrel** [comment] 2018-07-12 23:45
I can confirm that as of 7/12/2018 that this issue is still present. Installing this along with Valkyrien Warfare does in fact cause vehicles from Minecraft Transport Simulator to fall through the ground.

**Comment by LemADEC** [comment] 2018-07-13 19:09
We need version numbers boys and girls, exact version labels of all mods involved

**Comment by Nianor** [comment] 2018-07-13 20:20
Testing it with 0.9 pre 5 and MTS 10.1.2 on 1.12.2.

**Comment by Nianor** [comment] 2018-07-13 20:51
And, as per every bug report we've received on the subject, any attempt to place a vehicle results in it instantly falling through the ground.
![2018-07-13_13 50 06_2](https://user-images.githubusercontent.com/11527859/42713311-e1b47fb2-86a3-11e8-8937-208c21217259.png)

**Comment by LemADEC** [comment] 2018-07-14 08:15
So the vehicule are partially sinking into the ground?
is it reproduced in single player? in a dedicated server?

**Comment by Nianor** [comment] 2018-07-14 08:31
No, the vehicles don’t collide with anything, they fall into the void.
The issue has been observed in singleplayer and on a server.

**Comment by Rubyjunk** [comment] 2019-08-22 03:02
Thank you so much for your report. I'm opting to close this as a duplicate of #183 (though I now this came first), which you may follow if you're interested. 

With <3,
Valkyrien Warfare Team

**Closed by Rubyjunk** 2019-08-22 03:02 UTC
