### ISSUE TITLE
Minecolonies Buildtool Crash

### ISSUE THREAD

**Issue by WenXin20** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#63] opened 2017-02-24 23:48 UTC
**Minecolonies version**

Version 0.6.2849, Forge 2221

**Valkyrien Warfare version**

Version 0.8.7b

**Expected behavior**

No crash while changing the decoration type.

**Actual behaviour**

The build tool crashes in the decorations tab once I click the button that says walls.
The crash log also mentions something about the Valkyrien Warfare Mod.

**Steps to reproduce the problem**

1. Right-Click the minecolonies build tool.
2. Click the button that takes you to the decoration tab.
3. Press the button that says walls.
4. Crash

[Crash Report-client](http://pastebin.com/mYffQne6)
[Crash Report-server](http://pastebin.com/Pjgk2gwE)

It was previously reported at Minecolonies/minecolonies#604, but they said there's probably nothing they can do. Is there anything that can be done on your side?

**Comment by BigBastard** [comment] 2017-03-09 22:59
I've located the cause of the crash, and have since patched it. The game won't crash anymore with Minecolonies, but most of the features won't work on a ship. Adding feature compatibility would require serious rewrites on their end. :/

Anyways, crash has been fixed so I'm closing this issue; be sure to let me know if any other problems with MineColonies ever come up.

**Closed by BigBastard** 2017-03-09 22:59 UTC

**Comment by WenXin20** [comment] 2017-03-10 02:43
Thanks
