### ISSUE TITLE
Old maps crash

### ISSUE THREAD

**Issue by Diegoddk** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#43] opened 2017-02-06 20:48 UTC
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.10.2-0006-full.jar)
  ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.7-65.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 06/02/17 05:43 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2482)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1715)
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:175)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:597)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:524)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:474)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 499695608 bytes (476 MB) / 1086115840 bytes (1035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	movingworld{1.10.2-0006} [Moving World] (movingworld-1.10.2-0006-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0006-full.jar) 
	UCHIJAAAA	valkyrienwarfare{0.87a} [Valkyrien Warfare] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfarecombat{0.1} [Valkyrien Warfare Combat] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfarecontrol{0.3b} [Valkyrien Warfare Control] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	can{can} [can] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfareworld{0.0a} [Valkyrien Warfare World] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	XaeroMinimap{1.11.4} [Xaero's Minimap] (Xaeros_Minimap_1.11.4_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.10.2-0006-full.jar)
  
ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.7-65.jar)
  ValkyrienWarfareBase.CoreMod.ValkyrienWarfareTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Diegox64'/26, l='Earth New', x=2148,85, y=60,69, z=3328,35]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by DaMatrix** [comment] 2017-02-06 22:17
You sure that that's caused by Valkyrien Warfare? I've never seen an error like that and davinci's vessels seems to be in the mod environment. 

-------- Original message --------

**Comment by rinesi** [comment] 2017-02-07 03:23
Its definitely Valkyrien Warfare

[crash-2017-02-06_22.08.43-server.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/756500/crash-2017-02-06_22.08.43-server.txt)

Heres another log from my server.

**Comment by Diegoddk** [comment] 2017-02-07 20:44
I deleted the davincis vessels mod and it still happens heres another log:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.7-65.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 07/02/17 05:40 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1
	at net.minecraft.entity.Entity.func_85029_a(Entity.java:2482)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1715)
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:175)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:597)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:524)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:474)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 485781872 bytes (463 MB) / 1100431360 bytes (1049 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	valkyrienwarfare{0.87a} [Valkyrien Warfare] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfarecombat{0.1} [Valkyrien Warfare Combat] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfarecontrol{0.3b} [Valkyrien Warfare Control] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	can{can} [can] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	valkyrienwarfareworld{0.0a} [Valkyrien Warfare World] (valkyrienwarfare-1.10.2-0.8.7-65.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	XaeroMinimap{1.11.4} [Xaero's Minimap] (Xaeros_Minimap_1.11.4_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.7-65.jar)
  ValkyrienWarfareBase.CoreMod.ValkyrienWarfareTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Diegox64'/26, l='Earth New', x=2175,78, y=62,88, z=3372,46]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by DaMatrix** [comment] 2017-02-07 21:05
Hm. @BigBastard do we do ASM on `Entity#func_85029_a`?

**Comment by BigBastard** [comment] 2017-03-20 05:42
Fixed in 24a2f504c3dc35e596839a8d7a2d14633cb5ad05

Closing

**Closed by BigBastard** 2017-03-20 05:42 UTC
