### ISSUE TITLE
MTS vehicles sink through the ground with this mod installed

### ISSUE THREAD

**Issue by TheCactus27** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#211] opened 2019-01-18 20:46 UTC
MTS vehicles sink through the ground. The MTS dev says this is due to your collision system.

**Comment by Rubyjunk** [comment] 2019-08-22 03:02
Thank you so much for your report. This happens to be a duplicate of #183, which you may follow if you're interested. 

With <3,
Valkyrien Warfare Team

**Closed by Rubyjunk** 2019-08-22 03:02 UTC
