### ISSUE TITLE
Sneak + Rightclick with a block/item in hand on a block with an inventory/UI works wrongly

### ISSUE THREAD

**Issue by TeetoKaziim** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#120] opened 2018-02-04 06:38 UTC
Minecraft: 1.12.2
Forge: 14.23.2.2611
Valkyrien Warfare: ValkyrianWarfareRevamped-1.12.2-v0.9_alpha-full

Other mods:
Hwyla: 1.8.23-B38_1.12
Just Enough Items (JEI): 1.12.2-4.8.5.147
_(Also tested both with and without: Advanced Rocketry 1.12.2-1.2.6-54)_

Normally, in minecraft, when holding a block, such as a hopper, in your main hand, if you sneak while rightclicking with it, it will place the block, even if your crosshairs are pointed at a block with an inventory or UI like a Chest, or Furnace.

With Valkyrien Warfare installed, instead, the block is not placed, and instead the UI for the targetted block is opened instead.

This also interferes with Advanced Rocketry's "Linker" tool, which is a held item that records the coordinates of blocks you shift-right-click-on, for the purposes of helping them interact with that mod's rocket entities. Most of them are blocks with inventories/UI's. The linker fails to record any coordinates.

Thanks for your time and consideration.

**Comment by DaMatrix** [comment] 2018-02-04 12:06
I think I saw something about this a while back but was unable to reproduce it. I'll dig around and see what I can find :D

**Comment by DaMatrix** [comment] 2018-02-04 12:28
Should be fixed.

**Closed** 2018-02-04 12:27 UTC
Labels: bug

**Comment by TeetoKaziim** [comment] 2018-02-04 16:38
Thanks a bazillion! :D
